spring:
  application:
    frontend-base-url: ${FRONTEND_BASE_URL}
    name: social-commerce-be

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${REDIRECT_URL}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRY}

superbase:
  auth-token: ${SUPERBASE_AUTH_TOKEN}

x-aggregator:
  notification-url: ${PAYMENT_NOTIFICATION_URL}
  redirect-url: ${PAYMENT_REDIRECT_URL}
  secret-key: ${PAYMENT_SECRET_KEY}
